name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        
    - name: Deploy to gh-pages
      run: |
        # Create a clean gh-pages branch
        git checkout --orphan gh-pages-temp
        
        # Copy only app files to root
        cp app/* .
        rm -rf app/ docs/ research/ tools/ *.md *.code-workspace .gitignore
        
        # Commit and force push to gh-pages
        git add .
        git commit -m "🚀 Auto-deploy: $(date '+%Y-%m-%d %H:%M:%S')"
        git branch -D gh-pages || true
        git branch -m gh-pages
        git push -f origin gh-pages
        
        # Return to main branch
        git checkout main

permissions:
  contents: write 